### ISSUE TITLE
annoy fails

### ISSUE THREAD

**Issue by midick** [surprisetalk/nowify#6]
Hi,
I really like the idea of nowify and installed it as soon as I heard about it.
I set up a small routines file and `nowify cli` as well as `nowify stats` work fine.

However `nowify annoy` throws:
```
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    at opRun (ext:runtime/40_process.js:58:10)
    at Object.run (ext:runtime/40_process.js:155:15)
    at file:///home/dick/software/nowify/nowify.ts:198:18
    at eventLoopTick (ext:core/01_core.js:169:7)
```

do you have any idea what might be causing this?
I am on Linux , so maybe the sound file not being where nowify expects it (I didn't find one in the repo, so I assume it uses a system sound)

**Comment by surprisetalk** [comment]
Ah, `afplay` and the sound file are specific to MacOS.

I recommend opening a PR with one of the following fixes:
- hard: using a javascript-based tone generator so that we can bundle it with no CLI dependencies
- easy: adding the annoy command as a cli input, so that you can pass in any sound-making script that you want, e.g. `nowify annoy -c "afplay frog.mp3"`

**Comment by midick** [comment]
thank you! 
makes sense,
I'll go with the easy option and create the PR once I have some time
